AWSTemplateFormatVersion: '2010-09-09'
Description: "A sample template"
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "dhruv.aws.demo.example.com" 
      VersioningConfiguration:
        Status: Enabled
        